### ISSUE TITLE
Add lock to game pad 

### ISSUE THREAD

**Issue by DKassab1425** [errorcodexero/swimmy2023#11]
Add lock to right trigger on game pad

**Comment by sjcbulldog** [comment]
I am not sure about this.  I can see the driver pressing lock when the gunner has not set all of the switches and the gunner needing abort and get things set up again.  Since the lock is only valid after the switches are all set, I think lock needs to remain a gunner only thing.  The coach should be telling the drive team where to go, the gunner should be setting up the robot, and the driver should be driving to the right april tag.

**Comment by DKassab1425** [comment]
I’ll agree that most of the time, the gunner should be pressing it although I still think both should have control. For example, if we want to do ground collect, when the robot moves to the collection position is highly dependent on how Alex is going to drive and how he will get there which only he knows. This robot is so fast, having the driver to gunner delay for at least this situation would slow things down. 

We also need to train Lily to not wait to lock. If she knows what needs to be done next, the robot should be locked as soon as she has the switches ready.

**Comment by sjcbulldog** [comment]
So what about having the lock work only if we are doing ground collect.  Also, I agree with lily on locking right away and not waiting.  Lets talk with her about this tonight.

**Comment by sjcbulldog** [comment]
This works as described for ground collect.
